version: '3.2'
services:
    app:
        build: .
        ports:
            - "5000:5000"
        environment:
            PYTHONDONTWRITEBYTECODE: 1
            FLASK_DEBUG: 1
            FREE_CURRENCY_API_BASE_URL: https://freecurrencyapi.net/api/v1
        volumes:
            - .:/usr/src/app
